-- ⚠️ Reset All Data
DROP SCHEMA public CASCADE;
CREATE SCHEMA public;
GRANT ALL ON SCHEMA public TO postgres;
GRANT ALL ON SCHEMA public TO anon;
GRANT ALL ON SCHEMA public TO authenticated;
GRANT ALL ON SCHEMA public TO service_role;

-- 1. Categories Table (New Structure)
CREATE TABLE public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    recommendation_weight INT DEFAULT 1
);

-- 2. Products Table (Added "is_recommended")
CREATE TABLE public.products (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name TEXT NOT NULL,
    price INT NOT NULL,
    category_id BIGINT REFERENCES public.categories(id),
    image_url TEXT,
    is_active BOOLEAN DEFAULT true,
    is_verified BOOLEAN DEFAULT false, -- True if categorized by script/human
    is_recommended BOOLEAN DEFAULT false, -- ★New: For "Recommended-First" logic
    is_temporary BOOLEAN DEFAULT false, -- ★New: For "Limited Time" items
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- For existing databases, run:
-- ALTER TABLE public.products ADD COLUMN is_temporary BOOLEAN DEFAULT false;

-- 3. Product Barcodes Table
CREATE TABLE public.product_barcodes (
    jan_code TEXT PRIMARY KEY,
    product_id UUID REFERENCES public.products(id) ON DELETE CASCADE
);

-- 4. Classification Votes Table (For Game)
CREATE TABLE public.classification_votes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id UUID REFERENCES public.products(id) ON DELETE CASCADE,
    voted_category_id BIGINT REFERENCES public.categories(id),
    session_id UUID, -- For anonymous user tracking
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Row Level Security (RLS) Setup
alter table public.categories enable row level security;
create policy "Public categories are viewable by everyone" on public.categories for select using (true);

alter table public.products enable row level security;
create policy "Public products are viewable by everyone" on public.products for select using (true);

alter table public.product_barcodes enable row level security;
create policy "Public barcodes are viewable by everyone" on public.product_barcodes for select using (true);

alter table public.classification_votes enable row level security;
create policy "Users can insert their own votes" on public.classification_votes for insert with check (true); -- Allow anon insert for MVP
create policy "Users can view their own votes" on public.classification_votes for select using (true);

-- Seed Data: Categories
INSERT INTO public.categories (slug, name, recommendation_weight) VALUES
('bento', '弁当・丼', 1),    -- ID:1 (Main)
('drink', '飲料', 1),       -- ID:2
('snack', 'お菓子', 1),     -- ID:3
('dessert', 'デザート', 1),  -- ID:4
('unknown', '不明', 0),     -- ID:5
('deli', '惣菜', 1),        -- ID:6
('noodle', '麺類・汁物', 1), -- ID:7
('onigiri', 'おにぎり', 1);  -- ID:8
